[poki_auds]
title = Poki AUDS
group = Distribution
help = Settings for the Poki AUDS extension

game_id.type = string
game_id.label = Game ID

remote_config_key.type = string
remote_config_key.label = Remote Config Key
remote_config_key.default = config

remote_config_id.type = string
remote_config_id.label = Remote Config ID

remote_config_json_file.type = string
remote_config_json_file.label = Remote Config JSON File
remote_config_json_file.default = remote_config.json

remote_config_secret_file.type = string
remote_config_secret_file.label = Remote Config Secret File
remote_config_secret_file.default = remote_config.secret

